In [1]:
import pandas as pd

In [2]:
df0 = pd.read_csv('./hourly.csv', encoding='utf-8')
df1 = pd.read_csv('./daily.csv', encoding='utf-8')
df2 = pd.read_csv('./monthly.csv', encoding='utf-8')
df3 = pd.read_csv('./yearly.csv', encoding='utf-8')

In [3]:
df1.loc[df1['province'].str.contains('台湾')]

,Unnamed: 0,province,city,pm2.5,pm10,so2,no2,co,o3,U,V,temp,rh,psfc,date
30,30,台湾省,[],19.303924,23.121392,6.845000,19.015759,0.260253,48.526835,-0.925823,-1.259430,285.022532,79.375127,93328.395380,2013-01-01
400,400,台湾省,[],15.921899,19.734494,5.926076,19.021582,0.243228,52.047975,-0.456646,-2.373987,288.069620,82.204937,93441.978861,2013-01-02
770,770,台湾省,[],15.254430,23.593418,4.898924,11.317342,0.273924,52.091899,-3.206962,-6.462342,287.710696,82.666519,93587.988861,2013-01-03
1140,1140,台湾省,[],9.029937,15.409557,4.032532,11.993924,0.241139,54.888734,-2.269557,-4.569684,286.963734,82.171392,93385.824367,2013-01-04
1510,1510,台湾省,[],9.823924,16.229747,4.598608,15.637025,0.229177,52.287595,-0.772468,-4.096519,287.627975,83.982342,93141.859494,2013-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808850,808850,台湾省,[],21.123861,29.711899,7.629684,16.953481,0.290633,49.369810,-1.555823,-5.651203,289.368418,76.995000,93106.481203,2018-12-27
809220,809220,台湾省,[],9.475000,15.825949,4.392595,8.676076,0.235127,59.737722,-4.614494,-7.331392,287.301013,76.220886,93484.040190,2018-12-28
809590,809590,台湾省,[],14.145696,19.836203,6.628165,11.059684,0.279557,54.891076,-4.234177,-7.159810,285.077342,73.488544,93791.718924,2018-12-29
809960,809960,台湾省,[],7.693734,12.266772,3.906456,9.551456,0.230886,66.740190,-4.685190,-5.542089,286.746456,74.355570,93825.433608,2018-12-30
810330,810330,台湾省,[],7.237658,12.610886,3.762532,9.860443,0.229241,61.677342,-3.407342,-6.117025,288.250190,78.755633,93886.350316,2018-12-31

In [4]:
df0 = df0.loc[~df0['province'].str.contains('台湾')]
df1 = df1.loc[~df1['province'].str.contains('台湾')]
df2 = df2.loc[~df2['province'].str.contains('台湾')]
df3 = df3.loc[~df3['province'].str.contains('台湾')]

In [5]:
df0.to_csv('hourly_new.csv', encoding='utf-8-sig', index = False)
df1.to_csv('daily_new.csv', encoding='utf-8-sig', index = False)
df2.to_csv('monthly_new.csv', encoding='utf-8-sig', index = False)
df3.to_csv('yearly_new.csv', encoding='utf-8-sig', index = False)